//
// The Open Toolkit Library License
//
// Copyright (c) 2006 - 2013 Stefanos Apostolopoulos for the Open Toolkit Library
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to 
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

namespace OpenTK.Graphics.ES20
{
    using System;
    using System.Text;
    using System.Runtime.InteropServices;
    #pragma warning disable 3019
    #pragma warning disable 1591
    #pragma warning disable 1572
    #pragma warning disable 1573
    #pragma warning disable 626

    partial class GL
    {
        public static partial class Intel
        {
            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glBeginPerfQueryINTEL")]
            [CLSCompliant(false)]
            public static void BeginPerfQuery(Int32 queryHandle) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glBeginPerfQueryINTEL")]
            [CLSCompliant(false)]
            public static void BeginPerfQuery(UInt32 queryHandle) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="queryHandle"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glCreatePerfQueryINTEL")]
            [CLSCompliant(false)]
            public static void CreatePerfQuery(Int32 queryId, [OutAttribute] Int32[] queryHandle) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="queryHandle"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glCreatePerfQueryINTEL")]
            [CLSCompliant(false)]
            public static void CreatePerfQuery(Int32 queryId, [OutAttribute] out Int32 queryHandle) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="queryHandle"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glCreatePerfQueryINTEL")]
            [CLSCompliant(false)]
            public static unsafe void CreatePerfQuery(Int32 queryId, [OutAttribute] Int32* queryHandle) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="queryHandle"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glCreatePerfQueryINTEL")]
            [CLSCompliant(false)]
            public static void CreatePerfQuery(UInt32 queryId, [OutAttribute] UInt32[] queryHandle) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="queryHandle"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glCreatePerfQueryINTEL")]
            [CLSCompliant(false)]
            public static void CreatePerfQuery(UInt32 queryId, [OutAttribute] out UInt32 queryHandle) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="queryHandle"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glCreatePerfQueryINTEL")]
            [CLSCompliant(false)]
            public static unsafe void CreatePerfQuery(UInt32 queryId, [OutAttribute] UInt32* queryHandle) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glDeletePerfQueryINTEL")]
            [CLSCompliant(false)]
            public static void DeletePerfQuery(Int32 queryHandle) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glDeletePerfQueryINTEL")]
            [CLSCompliant(false)]
            public static void DeletePerfQuery(UInt32 queryHandle) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glEndPerfQueryINTEL")]
            [CLSCompliant(false)]
            public static void EndPerfQuery(Int32 queryHandle) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glEndPerfQueryINTEL")]
            [CLSCompliant(false)]
            public static void EndPerfQuery(UInt32 queryHandle) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetFirstPerfQueryIdINTEL")]
            [CLSCompliant(false)]
            public static Int32 GetFirstPerfQueryI() { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetFirstPerfQueryIdINTEL")]
            [CLSCompliant(false)]
            public static void GetFirstPerfQueryI([OutAttribute] Int32[] queryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetFirstPerfQueryIdINTEL")]
            [CLSCompliant(false)]
            public static void GetFirstPerfQueryI([OutAttribute] out Int32 queryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetFirstPerfQueryIdINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetFirstPerfQueryI([OutAttribute] Int32* queryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetFirstPerfQueryIdINTEL")]
            [CLSCompliant(false)]
            public static void GetFirstPerfQueryI([OutAttribute] UInt32[] queryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetFirstPerfQueryIdINTEL")]
            [CLSCompliant(false)]
            public static void GetFirstPerfQueryI([OutAttribute] out UInt32 queryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetFirstPerfQueryIdINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetFirstPerfQueryI([OutAttribute] UInt32* queryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetNextPerfQueryIdINTEL")]
            [CLSCompliant(false)]
            public static Int32 GetNextPerfQueryI(Int32 queryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetNextPerfQueryIdINTEL")]
            [CLSCompliant(false)]
            public static Int32 GetNextPerfQueryI(UInt32 queryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="nextQueryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetNextPerfQueryIdINTEL")]
            [CLSCompliant(false)]
            public static void GetNextPerfQueryI(Int32 queryId, [OutAttribute] Int32[] nextQueryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="nextQueryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetNextPerfQueryIdINTEL")]
            [CLSCompliant(false)]
            public static void GetNextPerfQueryI(Int32 queryId, [OutAttribute] out Int32 nextQueryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="nextQueryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetNextPerfQueryIdINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetNextPerfQueryI(Int32 queryId, [OutAttribute] Int32* nextQueryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="nextQueryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetNextPerfQueryIdINTEL")]
            [CLSCompliant(false)]
            public static void GetNextPerfQueryI(UInt32 queryId, [OutAttribute] UInt32[] nextQueryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="nextQueryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetNextPerfQueryIdINTEL")]
            [CLSCompliant(false)]
            public static void GetNextPerfQueryI(UInt32 queryId, [OutAttribute] out UInt32 nextQueryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="nextQueryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetNextPerfQueryIdINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetNextPerfQueryI(UInt32 queryId, [OutAttribute] UInt32* nextQueryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="counterId"></param>
            /// <param name="counterNameLength"></param>
            /// <param name="counterName"></param>
            /// <param name="counterDescLength"></param>
            /// <param name="counterDesc"></param>
            /// <param name="counterOffset"></param>
            /// <param name="counterDataSize"></param>
            /// <param name="counterTypeEnum"></param>
            /// <param name="counterDataTypeEnum"></param>
            /// <param name="rawCounterMaxValue"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfCounterInfoINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfCounterInfo(Int32 queryId, Int32 counterId, Int32 counterNameLength, [OutAttribute] StringBuilder counterName, Int32 counterDescLength, [OutAttribute] StringBuilder counterDesc, [OutAttribute] Int32[] counterOffset, [OutAttribute] Int32[] counterDataSize, [OutAttribute] Int32[] counterTypeEnum, [OutAttribute] Int32[] counterDataTypeEnum, [OutAttribute] Int64[] rawCounterMaxValue) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="counterId"></param>
            /// <param name="counterNameLength"></param>
            /// <param name="counterName"></param>
            /// <param name="counterDescLength"></param>
            /// <param name="counterDesc"></param>
            /// <param name="counterOffset"></param>
            /// <param name="counterDataSize"></param>
            /// <param name="counterTypeEnum"></param>
            /// <param name="counterDataTypeEnum"></param>
            /// <param name="rawCounterMaxValue"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfCounterInfoINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfCounterInfo(Int32 queryId, Int32 counterId, Int32 counterNameLength, [OutAttribute] StringBuilder counterName, Int32 counterDescLength, [OutAttribute] StringBuilder counterDesc, [OutAttribute] out Int32 counterOffset, [OutAttribute] out Int32 counterDataSize, [OutAttribute] out Int32 counterTypeEnum, [OutAttribute] out Int32 counterDataTypeEnum, [OutAttribute] out Int64 rawCounterMaxValue) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="counterId"></param>
            /// <param name="counterNameLength"></param>
            /// <param name="counterName"></param>
            /// <param name="counterDescLength"></param>
            /// <param name="counterDesc"></param>
            /// <param name="counterOffset"></param>
            /// <param name="counterDataSize"></param>
            /// <param name="counterTypeEnum"></param>
            /// <param name="counterDataTypeEnum"></param>
            /// <param name="rawCounterMaxValue"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfCounterInfoINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfCounterInfo(Int32 queryId, Int32 counterId, Int32 counterNameLength, [OutAttribute] StringBuilder counterName, Int32 counterDescLength, [OutAttribute] StringBuilder counterDesc, [OutAttribute] Int32* counterOffset, [OutAttribute] Int32* counterDataSize, [OutAttribute] Int32* counterTypeEnum, [OutAttribute] Int32* counterDataTypeEnum, [OutAttribute] Int64* rawCounterMaxValue) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="counterId"></param>
            /// <param name="counterNameLength"></param>
            /// <param name="counterName"></param>
            /// <param name="counterDescLength"></param>
            /// <param name="counterDesc"></param>
            /// <param name="counterOffset"></param>
            /// <param name="counterDataSize"></param>
            /// <param name="counterTypeEnum"></param>
            /// <param name="counterDataTypeEnum"></param>
            /// <param name="rawCounterMaxValue"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfCounterInfoINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfCounterInfo(UInt32 queryId, UInt32 counterId, UInt32 counterNameLength, [OutAttribute] StringBuilder counterName, UInt32 counterDescLength, [OutAttribute] StringBuilder counterDesc, [OutAttribute] UInt32[] counterOffset, [OutAttribute] UInt32[] counterDataSize, [OutAttribute] UInt32[] counterTypeEnum, [OutAttribute] UInt32[] counterDataTypeEnum, [OutAttribute] UInt64[] rawCounterMaxValue) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="counterId"></param>
            /// <param name="counterNameLength"></param>
            /// <param name="counterName"></param>
            /// <param name="counterDescLength"></param>
            /// <param name="counterDesc"></param>
            /// <param name="counterOffset"></param>
            /// <param name="counterDataSize"></param>
            /// <param name="counterTypeEnum"></param>
            /// <param name="counterDataTypeEnum"></param>
            /// <param name="rawCounterMaxValue"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfCounterInfoINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfCounterInfo(UInt32 queryId, UInt32 counterId, UInt32 counterNameLength, [OutAttribute] StringBuilder counterName, UInt32 counterDescLength, [OutAttribute] StringBuilder counterDesc, [OutAttribute] out UInt32 counterOffset, [OutAttribute] out UInt32 counterDataSize, [OutAttribute] out UInt32 counterTypeEnum, [OutAttribute] out UInt32 counterDataTypeEnum, [OutAttribute] out UInt64 rawCounterMaxValue) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="counterId"></param>
            /// <param name="counterNameLength"></param>
            /// <param name="counterName"></param>
            /// <param name="counterDescLength"></param>
            /// <param name="counterDesc"></param>
            /// <param name="counterOffset"></param>
            /// <param name="counterDataSize"></param>
            /// <param name="counterTypeEnum"></param>
            /// <param name="counterDataTypeEnum"></param>
            /// <param name="rawCounterMaxValue"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfCounterInfoINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfCounterInfo(UInt32 queryId, UInt32 counterId, UInt32 counterNameLength, [OutAttribute] StringBuilder counterName, UInt32 counterDescLength, [OutAttribute] StringBuilder counterDesc, [OutAttribute] UInt32* counterOffset, [OutAttribute] UInt32* counterDataSize, [OutAttribute] UInt32* counterTypeEnum, [OutAttribute] UInt32* counterDataTypeEnum, [OutAttribute] UInt64* rawCounterMaxValue) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData(Int32 queryHandle, Int32 flags, Int32 dataSize, [OutAttribute] IntPtr data, [OutAttribute] Int32[] bytesWritten) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData(Int32 queryHandle, Int32 flags, Int32 dataSize, [OutAttribute] IntPtr data, [OutAttribute] out Int32 bytesWritten) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfQueryData(Int32 queryHandle, Int32 flags, Int32 dataSize, [OutAttribute] IntPtr data, [OutAttribute] Int32* bytesWritten) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(Int32 queryHandle, Int32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[] data, [OutAttribute] Int32[] bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(Int32 queryHandle, Int32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[] data, [OutAttribute] out Int32 bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfQueryData<T3>(Int32 queryHandle, Int32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[] data, [OutAttribute] Int32* bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(Int32 queryHandle, Int32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[,] data, [OutAttribute] Int32[] bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(Int32 queryHandle, Int32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[,] data, [OutAttribute] out Int32 bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfQueryData<T3>(Int32 queryHandle, Int32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[,] data, [OutAttribute] Int32* bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(Int32 queryHandle, Int32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[,,] data, [OutAttribute] Int32[] bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(Int32 queryHandle, Int32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[,,] data, [OutAttribute] out Int32 bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfQueryData<T3>(Int32 queryHandle, Int32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[,,] data, [OutAttribute] Int32* bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(Int32 queryHandle, Int32 flags, Int32 dataSize, [InAttribute, OutAttribute] ref T3 data, [OutAttribute] Int32[] bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(Int32 queryHandle, Int32 flags, Int32 dataSize, [InAttribute, OutAttribute] ref T3 data, [OutAttribute] out Int32 bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfQueryData<T3>(Int32 queryHandle, Int32 flags, Int32 dataSize, [InAttribute, OutAttribute] ref T3 data, [OutAttribute] Int32* bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData(UInt32 queryHandle, UInt32 flags, Int32 dataSize, [OutAttribute] IntPtr data, [OutAttribute] UInt32[] bytesWritten) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData(UInt32 queryHandle, UInt32 flags, Int32 dataSize, [OutAttribute] IntPtr data, [OutAttribute] out UInt32 bytesWritten) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfQueryData(UInt32 queryHandle, UInt32 flags, Int32 dataSize, [OutAttribute] IntPtr data, [OutAttribute] UInt32* bytesWritten) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(UInt32 queryHandle, UInt32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[] data, [OutAttribute] UInt32[] bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(UInt32 queryHandle, UInt32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[] data, [OutAttribute] out UInt32 bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfQueryData<T3>(UInt32 queryHandle, UInt32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[] data, [OutAttribute] UInt32* bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(UInt32 queryHandle, UInt32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[,] data, [OutAttribute] UInt32[] bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(UInt32 queryHandle, UInt32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[,] data, [OutAttribute] out UInt32 bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfQueryData<T3>(UInt32 queryHandle, UInt32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[,] data, [OutAttribute] UInt32* bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(UInt32 queryHandle, UInt32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[,,] data, [OutAttribute] UInt32[] bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(UInt32 queryHandle, UInt32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[,,] data, [OutAttribute] out UInt32 bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfQueryData<T3>(UInt32 queryHandle, UInt32 flags, Int32 dataSize, [InAttribute, OutAttribute] T3[,,] data, [OutAttribute] UInt32* bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(UInt32 queryHandle, UInt32 flags, Int32 dataSize, [InAttribute, OutAttribute] ref T3 data, [OutAttribute] UInt32[] bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryData<T3>(UInt32 queryHandle, UInt32 flags, Int32 dataSize, [InAttribute, OutAttribute] ref T3 data, [OutAttribute] out UInt32 bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryHandle"></param>
            /// <param name="flags"></param>
            /// <param name="dataSize"></param>
            /// <param name="data"></param>
            /// <param name="bytesWritten"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryDataINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfQueryData<T3>(UInt32 queryHandle, UInt32 flags, Int32 dataSize, [InAttribute, OutAttribute] ref T3 data, [OutAttribute] UInt32* bytesWritten)
                where T3 : struct
             { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryName"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryIdByNameINTEL")]
            [CLSCompliant(false)]
            public static Int32 GetPerfQueryIdByName([OutAttribute] StringBuilder queryName) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryName"></param>
            /// <param name="queryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryIdByNameINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryIdByName([OutAttribute] StringBuilder queryName, [OutAttribute] Int32[] queryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryName"></param>
            /// <param name="queryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryIdByNameINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryIdByName([OutAttribute] StringBuilder queryName, [OutAttribute] out Int32 queryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryName"></param>
            /// <param name="queryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryIdByNameINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfQueryIdByName([OutAttribute] StringBuilder queryName, [OutAttribute] Int32* queryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryName"></param>
            /// <param name="queryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryIdByNameINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryIdByName([OutAttribute] StringBuilder queryName, [OutAttribute] UInt32[] queryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryName"></param>
            /// <param name="queryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryIdByNameINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryIdByName([OutAttribute] StringBuilder queryName, [OutAttribute] out UInt32 queryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryName"></param>
            /// <param name="queryId"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryIdByNameINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfQueryIdByName([OutAttribute] StringBuilder queryName, [OutAttribute] UInt32* queryId) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="queryNameLength"></param>
            /// <param name="queryName"></param>
            /// <param name="dataSize"></param>
            /// <param name="noCounters"></param>
            /// <param name="noInstances"></param>
            /// <param name="capsMask"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryInfoINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryInfo(Int32 queryId, Int32 queryNameLength, [OutAttribute] StringBuilder queryName, [OutAttribute] Int32[] dataSize, [OutAttribute] Int32[] noCounters, [OutAttribute] Int32[] noInstances, [OutAttribute] Int32[] capsMask) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="queryNameLength"></param>
            /// <param name="queryName"></param>
            /// <param name="dataSize"></param>
            /// <param name="noCounters"></param>
            /// <param name="noInstances"></param>
            /// <param name="capsMask"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryInfoINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryInfo(Int32 queryId, Int32 queryNameLength, [OutAttribute] StringBuilder queryName, [OutAttribute] out Int32 dataSize, [OutAttribute] out Int32 noCounters, [OutAttribute] out Int32 noInstances, [OutAttribute] out Int32 capsMask) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="queryNameLength"></param>
            /// <param name="queryName"></param>
            /// <param name="dataSize"></param>
            /// <param name="noCounters"></param>
            /// <param name="noInstances"></param>
            /// <param name="capsMask"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryInfoINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfQueryInfo(Int32 queryId, Int32 queryNameLength, [OutAttribute] StringBuilder queryName, [OutAttribute] Int32* dataSize, [OutAttribute] Int32* noCounters, [OutAttribute] Int32* noInstances, [OutAttribute] Int32* capsMask) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="queryNameLength"></param>
            /// <param name="queryName"></param>
            /// <param name="dataSize"></param>
            /// <param name="noCounters"></param>
            /// <param name="noInstances"></param>
            /// <param name="capsMask"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryInfoINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryInfo(UInt32 queryId, UInt32 queryNameLength, [OutAttribute] StringBuilder queryName, [OutAttribute] UInt32[] dataSize, [OutAttribute] UInt32[] noCounters, [OutAttribute] UInt32[] noInstances, [OutAttribute] UInt32[] capsMask) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="queryNameLength"></param>
            /// <param name="queryName"></param>
            /// <param name="dataSize"></param>
            /// <param name="noCounters"></param>
            /// <param name="noInstances"></param>
            /// <param name="capsMask"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryInfoINTEL")]
            [CLSCompliant(false)]
            public static void GetPerfQueryInfo(UInt32 queryId, UInt32 queryNameLength, [OutAttribute] StringBuilder queryName, [OutAttribute] out UInt32 dataSize, [OutAttribute] out UInt32 noCounters, [OutAttribute] out UInt32 noInstances, [OutAttribute] out UInt32 capsMask) { throw new NotImplementedException(); }

            /// <summary>[requires: INTEL_performance_query]</summary>
            /// <param name="queryId"></param>
            /// <param name="queryNameLength"></param>
            /// <param name="queryName"></param>
            /// <param name="dataSize"></param>
            /// <param name="noCounters"></param>
            /// <param name="noInstances"></param>
            /// <param name="capsMask"></param>
            [AutoGenerated(Category = "INTEL_performance_query", Version = "", EntryPoint = "glGetPerfQueryInfoINTEL")]
            [CLSCompliant(false)]
            public static unsafe void GetPerfQueryInfo(UInt32 queryId, UInt32 queryNameLength, [OutAttribute] StringBuilder queryName, [OutAttribute] UInt32* dataSize, [OutAttribute] UInt32* noCounters, [OutAttribute] UInt32* noInstances, [OutAttribute] UInt32* capsMask) { throw new NotImplementedException(); }

        }
    	
    }
}
